In [5]:
import os
import numpy as np 
import pandas as pd

from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error

from sklearn.multioutput import MultiOutputRegressor
import matplotlib.pyplot as plt

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

from sklearn.model_selection import train_test_split


#THIS IS THE BEST MODEL TO DATE THAT I HAVE DONE. ACCURACY = 2.60

#TODO: incorportae train_model. 

#UPDATE: this has the best accuracy with 2.662!!! touse, best model. 

#UPDATE: when i tried to simplify it by adding the train_model to the 


In [3]:
X_train = pd.read_csv("data/ancestry_train.data", sep = " ", header=None).values
y_train = pd.read_csv("data/ancestry_train.solution", sep = " ", header=None).values

X_test = pd.read_csv("data/ancestry_test.data", sep = " ", header=None).values

In [6]:
np.round(y_train, 3)

X_train_split, X_val, y_train_split, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)


In [4]:
#try to build a multi-output model neural network. 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam


In [8]:
from keras.callbacks import EarlyStopping

def get_model(n_inputs, n_outputs):
    model = Sequential()
    model.add(Dense(50, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
    model.add(Dense(30, activation='relu'))
    model.add(Dense(n_outputs, activation='sigmoid'))  # Sigmoid activation for output layer
    model.compile(loss='mean_squared_error', optimizer='adam')  # Using mean squared error for loss
    return model

# Train the model
def train_model(X_train, y_train, X_val, y_val):
    model = get_model(X_train.shape[1], y_train.shape[1])
    early_stop = EarlyStopping(monitor='val_loss', patience=10, verbose=1, mode='min', restore_best_weights=True)

    history = model.fit(X_train, y_train, validation_data=(X_val, y_val),
                        epochs=100, batch_size=32, verbose=1, callbacks=[early_stop])
    return model, history

# Usage
#model, history = train_model(X_train, y_train, X_val, y_val)

In [9]:
model_touse = train_model(X_train_split, y_train_split, X_val, y_val)
# summarize performance
#print('MAE: %.3f (%.3f)' % (np.mean(results), np.std(results)))

Epoch 1/100
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0054 - val_loss: 0.0027
Epoch 2/100
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0024 - val_loss: 0.0022
Epoch 3/100
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0022 - val_loss: 0.0022
Epoch 4/100
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0021 - val_loss: 0.0021
Epoch 5/100
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0020 - val_loss: 0.0021
Epoch 6/100
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0020 - val_loss: 0.0022
Epoch 7/100
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0019 - val_loss: 0.0021
Epoch 8/100
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0018 - val_loss: 0.0022
Epoch 9/100
1000/1000 [==============================] - 2s 2ms/step - loss: 0.0017 - val_loss: 0.0022
Epoch 10/100
1000/1000 [==============================] - 2s 2ms/step - l

In [6]:
n_inputs, n_outputs = X_test.shape[1], y_train.shape[1]
# get model
model = get_model(n_inputs, n_outputs)
# fit the model on all data
model.fit(X_train, y_train, verbose=0, epochs=100)
# make a prediction for new data
newX = X_test
yhat = model.predict(newX)


print(yhat)

313/313 [==============================] - 1s 2ms/step
[[ 9.7959340e-03  3.9531535e-01  5.9403098e-01]
 [ 9.7517532e-01  2.0544261e-02 -6.7355111e-04]
 [ 5.7326853e-03  6.6763759e-03  9.9065584e-01]
 ...
 [ 2.0027429e-02  4.8545212e-01  4.9155781e-01]
 [-1.6391248e-02 -3.5119653e-02  1.0714254e+00]
 [ 5.0765276e-03  3.8240999e-02  9.5940810e-01]]


In [7]:
#normalize 

yhat[yhat < 0] = 0

normalized_yhat= yhat / np.sum(yhat, axis=1, keepdims=True)

print(normalized_yhat)

pd.DataFrame(normalized_yhat).to_csv(f"predictions.csv", sep = " ", header = None, index = None)
os.system("zip -r predictions.zip predictions.csv")

[[0.00980434 0.3956547  0.5945409 ]
 [0.97936743 0.02063258 0.        ]
 [0.00571517 0.00665598 0.9876289 ]
 ...
 [0.02008694 0.48689458 0.49301842]
 [0.         0.         1.        ]
 [0.00506273 0.03813705 0.9568002 ]]
updating: predictions.csv (deflated 58%)


0

In [17]:
yhat = model_touse[0].predict(X_test)
print(yhat)

#yhat[yhat < 0] = 0

#normalized_yhat= yhat / np.sum(yhat, axis=1, keepdims=True)

#print(normalized_yhat)

pd.DataFrame(yhat).to_csv(f"predictions.csv", sep = " ", header = None, index = None)
os.system("zip -r predictions.zip predictions.csv")

313/313 [==============================] - 0s 929us/step
[[2.7025884e-03 4.9857944e-01 4.8467928e-01]
 [9.7643310e-01 2.4460075e-02 2.0539868e-05]
 [1.4236641e-04 2.2574620e-02 9.7575921e-01]
 ...
 [4.9864701e-03 5.0396377e-01 4.8262763e-01]
 [2.5581877e-04 2.3059456e-02 9.7886539e-01]
 [9.5223979e-04 3.5895068e-02 9.6520430e-01]]
updating: predictions.csv (deflated 57%)


0